library(shiny)

shinyUI(pageWithSidebar(
  headerPanel("Forcasting diamond price based on features"),
  sidebarPanel(
    h4('Weight of the diamond'),
    sliderInput('carat', 'carat', value=1, min = 0.2, max = 5.01, 0.05),
    h4('Quality of the cut'),
    checkboxGroupInput("cut", "cut",
                       c("Fair" = 1,
                         "Good" = 2,
                         "Very Good" = 3,
                         "Premium" = 4,
                         "Ideal" = 5), selected=1),
    h4('Diamond color, from J(worst) to D(best)'),
    checkboxGroupInput("color", "color",
                       c("D" = 1,
                         "E" = 2,
                         "F" = 3,
                         "G" = 4,
                         "H" = 5,
                         "I" = 6,
                         "J" = 7), selected=1),
    h4('Clarity measurement, I1(worst), SI1, SI2, VS1, VS2, VVS1, VVS2, IF(best'),
    checkboxGroupInput("clarity", "clarity",
                       c("I1" = 1,
                         "SI2" = 2,
                         "SI1" = 3,
                         "VS2" = 4,
                         "VS1" = 5,
                         "VVS2" = 6,
                         "VVS1" = 7,
                         "IF" = 8), selected = 1),
    h4('X length in mm'),
    sliderInput('x', 'x', 1, min = 0, max = 10.74, 0.5),
    h4('Y width in mm'),
    sliderInput('y', 'y', 1, min = 0, max = 58.9, 0.5),
    h4('Z depth in mm'),
    sliderInput('z', 'z', 1, min = 0, max = 31.8, 0.5),
    h4('Depth: total depth percentage'),
    sliderInput('depth', 'depth percentage', 50, min = 43, max = 79, 1),
    h4('Table: width of top of diamond relative to widest point'),
    sliderInput('table', 'table', 50, min = 43, max = 95, 1),
    submitButton('Submit')
  ),
  mainPanel(
    h3('The predicted "price" for this diamond is:'),
    verbatimTextOutput("prediction"),
    h3('Inputed diamond features'),
    h4('You entered "carat"'),
    verbatimTextOutput("carat"),
    h4('You entered "cut level"'),
    verbatimTextOutput("cut"),
    h4('You entered "color level"'),
    verbatimTextOutput("color"),
    h4('You entered "clarity level"'),
    verbatimTextOutput("clarity"),
    h4('You entered "x"'),
    verbatimTextOutput("x"),
    h4('You entered "y"'),
    verbatimTextOutput("y"),
    h4('You entered "z"'),
    verbatimTextOutput("z"),
    h4('You entered "depth"'),
    verbatimTextOutput("depth"),
    h4('You entered "table"'),
    verbatimTextOutput("table"),
    h4('The summary of the prediction model is:'),
    verbatimTextOutput("modelfit"),
    h4('Standardized Residual Plot'),
    plotOutput('Modelplot')
  )
))
